# Generated by Django 6.0.4 on 2026-04-23 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('administradorid', models.AutoField(db_column='AdministradorId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('correo', models.CharField(db_column='Correo', max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('usuario', models.CharField(db_column='Usuario', max_length=50, unique=True)),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=255)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='FechaRegistro', null=True)),
            ],
            options={
                'db_table': 'Administradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('candidatoid', models.AutoField(db_column='CandidatoId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('correo', models.CharField(db_column='Correo', max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('fechanacimiento', models.DateField(db_column='FechaNacimiento')),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='FechaRegistro', null=True)),
            ],
            options={
                'db_table': 'Candidatos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatEstados',
            fields=[
                ('estadoid', models.AutoField(db_column='EstadoId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('contexto', models.CharField(db_column='Contexto', max_length=50)),
            ],
            options={
                'db_table': 'Cat_Estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatEstadosCiviles',
            fields=[
                ('estadocivilid', models.AutoField(db_column='EstadoCivilId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Cat_EstadosCiviles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatGeneros',
            fields=[
                ('generoid', models.AutoField(db_column='GeneroId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Cat_Generos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatHabilidades',
            fields=[
                ('habilidadid', models.AutoField(db_column='HabilidadId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Cat_Habilidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatIdiomas',
            fields=[
                ('idiomaid', models.AutoField(db_column='IdiomaId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Cat_Idiomas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatModalidades',
            fields=[
                ('modalidadid', models.AutoField(db_column='ModalidadId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Cat_Modalidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatNacionalidades',
            fields=[
                ('nacionalidadid', models.AutoField(db_column='NacionalidadId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Cat_Nacionalidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatNivelesEducativos',
            fields=[
                ('niveleducativoid', models.AutoField(db_column='NivelEducativoId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Cat_NivelesEducativos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatSectores',
            fields=[
                ('sectorid', models.AutoField(db_column='SectorId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Cat_Sectores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTiposEmpleo',
            fields=[
                ('tipoempleoid', models.AutoField(db_column='TipoEmpleoId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Cat_TiposEmpleo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTiposEmpresa',
            fields=[
                ('tipoempresaid', models.AutoField(db_column='TipoEmpresaId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Cat_TiposEmpresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculumid', models.AutoField(db_column='CurriculumId', primary_key=True, serialize=False)),
                ('profesion', models.CharField(db_column='Profesion', max_length=100)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='FechaRegistro', null=True)),
            ],
            options={
                'db_table': 'Curriculum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('departamentoid', models.AutoField(db_column='DepartamentoId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmpleoRequisitos',
            fields=[
                ('requisitoid', models.AutoField(db_column='RequisitoId', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('esobligatorio', models.BooleanField(blank=True, db_column='EsObligatorio', null=True)),
            ],
            options={
                'db_table': 'Empleo_Requisitos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('empleoid', models.AutoField(db_column='EmpleoId', primary_key=True, serialize=False)),
                ('nombreempleo', models.CharField(db_column='NombreEmpleo', max_length=150)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=500)),
                ('salario', models.DecimalField(blank=True, db_column='Salario', decimal_places=2, max_digits=10, null=True)),
                ('fechapublicacion', models.DateTimeField(blank=True, db_column='FechaPublicacion', null=True)),
                ('fechacierre', models.DateTimeField(blank=True, db_column='FechaCierre', null=True)),
            ],
            options={
                'db_table': 'Empleos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('empresaid', models.AutoField(db_column='EmpresaId', primary_key=True, serialize=False)),
                ('nombreempresa', models.CharField(db_column='NombreEmpresa', max_length=150)),
                ('correo', models.CharField(db_column='Correo', max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, db_column='FechaRegistro', null=True)),
            ],
            options={
                'db_table': 'Empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('experienciaid', models.AutoField(db_column='ExperienciaId', primary_key=True, serialize=False)),
                ('empresa', models.CharField(db_column='Empresa', max_length=150)),
                ('cargo', models.CharField(db_column='Cargo', max_length=100)),
                ('fechainicio', models.DateField(db_column='FechaInicio')),
                ('fechafin', models.DateField(blank=True, db_column='FechaFin', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=500, null=True)),
            ],
            options={
                'db_table': 'ExperienciaLaboral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('municipioid', models.AutoField(db_column='MunicipioId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
            ],
            options={
                'db_table': 'Municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('postulacionid', models.AutoField(db_column='PostulacionId', primary_key=True, serialize=False)),
                ('fechapostulacion', models.DateTimeField(blank=True, db_column='FechaPostulacion', null=True)),
            ],
            options={
                'db_table': 'Postulaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('referenciaid', models.AutoField(db_column='ReferenciaId', primary_key=True, serialize=False)),
                ('nombrecontacto', models.CharField(db_column='NombreContacto', max_length=150)),
                ('cargo', models.CharField(blank=True, db_column='Cargo', max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, db_column='Empresa', max_length=150, null=True)),
                ('telefono', models.CharField(db_column='Telefono', max_length=20)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Referencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacantes',
            fields=[
                ('vacanteid', models.AutoField(db_column='VacanteId', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('fechainicio', models.DateTimeField(blank=True, db_column='FechaInicio', null=True)),
                ('fechafin', models.DateTimeField(blank=True, db_column='FechaFin', null=True)),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Vacantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumHabilidades',
            fields=[
                ('curriculumid', models.ForeignKey(db_column='CurriculumId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ImpulsoNica.curriculum')),
            ],
            options={
                'db_table': 'Curriculum_Habilidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumIdiomas',
            fields=[
                ('curriculumid', models.ForeignKey(db_column='CurriculumId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ImpulsoNica.curriculum')),
                ('nivel', models.CharField(db_column='Nivel', max_length=50)),
            ],
            options={
                'db_table': 'Curriculum_Idiomas',
                'managed': False,
            },
        ),
    ]
